FROM   apache/apisix:3.9.1-debian
#RUN yum -y install wget && wget https://openresty.org/package/centos/openresty.repo && mv openresty.repo /etc/yum.repos.d/openresty.repo && yum-config-manager --add-repo https://repos.apiseven.com/packages/centos/apache-apisix.repo  
#RUN yum check-update 
#RUN  yum install openresty-resty openresty -y 
#RUN yum -y install apisix-2.13
